### ISSUE TITLE
Hover over SDK integrations logos on dark mode 

### ISSUE THREAD

**Issue by ivanatreblle** [Treblle/docs#3]
Apply the same transition properties on SDK integrations logos on hover on dark mode as they are on light mode

**Comment by DominusKelvin** [comment]
Hey @ivanatreblle I can't seem to find the PR for this issue.

**Comment by ivanatreblle** [comment]
https://github.com/Treblle/docs/pull/5
Its this one, i dont know why its missing, sorry
